description: "Read Filtering Walkthrough 1"

user_email: ""

experiment_suffix: ""

basename: "testing"

#url or path to the csv of samples (sample_basename,fq1,fq2,condition)
samples: units.tsv

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    treated-vs-untreated:
      - treated
      - untreated

read_filtering:
  trim_suffix: "trimmed"
  
  quality_assessment:
    fastqc_suffix: "_fastqc"

  trimmomatic:
    trim_cmd:  "ILLUMINACLIP:{}:2:40:15 LEADING:20 TRAILING:20 SLIDINGWINDOW:4:15 MINLEN:35"
    
  adapter_file:
    name : "TruSeq2-PE.fa"
    url  : "http://dib-training.ucdavis.edu.s3.amazonaws.com/mRNAseq-semi-2015-03-04/TruSeq2-PE.fa"

  interleaving:
    interleave_suffix: "pe"

  data_type: "pe"
